url = https://www.saucedemo.com/
username =standard_user
password =secret_sauce

browser = chrome
titleName =Swag Labs

menus = All Items,About,Logout,Reset App State
execution=remote
gridURL=http://192.168.29.217:4444